# Руководство по Pandas DataFrame

Полное практическое руководство по работе с DataFrame в библиотеке pandas.
Все примеры используют единый набор данных «Сотрудники компании».

**Разделы:**
1. Введение
2. Создание DataFrame
3. Чтение и запись данных
4. Просмотр и базовая информация
5. Выбор данных (индексация)
6. Фильтрация данных
7. Изменение данных
8. Работа с пропущенными значениями (NaN)
9. Сортировка
10. Группировка и агрегация
11. Объединение DataFrame
12. Применение функций
13. Работа со строками
14. Работа с датами
15. Статистические методы
16. Преобразования и реструктуризация
17. Дубликаты
18. Настройки отображения

In [1]:
import pandas as pd
import numpy as np

# Основной набор данных — сотрудники компании
data = {
    'Имя': ['Анна', 'Борис', 'Виктор', 'Галина', 'Дмитрий', 'Елена'],
    'Отдел': ['IT', 'Продажи', 'IT', 'HR', 'Продажи', 'IT'],
    'Возраст': [28, 35, 42, 31, 29, 38],
    'Зарплата': [75000, 62000, 95000, 58000, 64000, 82000],
    'Дата_приёма': ['2021-03-15', '2019-07-20', '2015-01-10', '2020-11-01', '2022-05-18', '2018-09-05'],
    'Рейтинг': [4.5, 3.8, 4.9, 4.2, None, 4.7]
}
df = pd.DataFrame(data)
df['Дата_приёма'] = pd.to_datetime(df['Дата_приёма'])

# Дополнительный DataFrame для примеров объединения
departments = pd.DataFrame({
    'Отдел': ['IT', 'Продажи', 'HR', 'Маркетинг'],
    'Бюджет': [500000, 300000, 150000, 200000],
    'Руководитель': ['Иванов', 'Петров', 'Сидорова', 'Козлов']
})

print('Данные загружены!')
df

Данные загружены!

       Имя    Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
0     Анна       IT       28     75000  2021-03-15      4.5
1    Борис  Продажи       35     62000  2019-07-20      3.8
2   Виктор       IT       42     95000  2015-01-10      4.9
3   Галина       HR       31     58000  2020-11-01      4.2
4  Дмитрий  Продажи       29     64000  2022-05-18      NaN
5    Елена       IT       38     82000  2018-09-05      4.7

# 1. Введение

## Что такое pandas и DataFrame

**pandas** — библиотека Python для работы с табличными и временными данными.
**DataFrame** — двумерная структура данных с именованными строками и столбцами, похожая на таблицу Excel или SQL.

## Установка и импорт

```bash
pip install pandas numpy
```

Стандартный импорт:
```python
import pandas as pd
import numpy as np
```

In [ ]:
# Проверка версии pandas
print('Версия pandas:', pd.__version__)
print('Версия numpy:', np.__version__)

# Пример создания простейшего DataFrame
simple_df = pd.DataFrame({'A': [1, 2, 3], 'B': ['x', 'y', 'z']})
print('\nПример DataFrame:')
print(simple_df)

Версия pandas: 2.2.2
Версия numpy: 2.0.2

Пример DataFrame:
   A  B
0  1  x
1  2  y
2  3  z

# 2. Создание DataFrame

DataFrame можно создать несколькими способами: из словаря, списков, CSV-файла и других источников.

## 2.1 Из словаря

**Синтаксис:** `pd.DataFrame({'col1': [...], 'col2': [...]})`

Ключи словаря становятся именами столбцов, значения — данными столбцов.

In [ ]:
# Создание DataFrame из словаря
df_from_dict = pd.DataFrame({
    'Имя': ['Анна', 'Борис', 'Виктор'],
    'Возраст': [28, 35, 42],
    'Зарплата': [75000, 62000, 95000]
})
print('DataFrame из словаря:')
df_from_dict

DataFrame из словаря:

      Имя  Возраст  Зарплата
0    Анна       28     75000
1   Борис       35     62000
2  Виктор       42     95000

## 2.2 Из списка списков

**Синтаксис:** `pd.DataFrame([[1,2],[3,4]], columns=['a','b'])`

Каждый вложенный список — одна строка DataFrame.

In [ ]:
# Создание DataFrame из списка списков
df_from_list = pd.DataFrame(
    [['Анна', 28, 75000],
     ['Борис', 35, 62000],
     ['Виктор', 42, 95000]],
    columns=['Имя', 'Возраст', 'Зарплата']
)
print('DataFrame из списка списков:')
df_from_list

DataFrame из списка списков:

      Имя  Возраст  Зарплата
0    Анна       28     75000
1   Борис       35     62000
2  Виктор       42     95000

## 2.3 Из списка словарей

**Синтаксис:** `pd.DataFrame([{'a':1,'b':2}, {'a':3,'b':4}])`

Каждый словарь — одна строка; ключи становятся столбцами.

In [ ]:
# Создание DataFrame из списка словарей
df_from_records = pd.DataFrame([
    {'Имя': 'Анна', 'Отдел': 'IT', 'Зарплата': 75000},
    {'Имя': 'Борис', 'Отдел': 'Продажи', 'Зарплата': 62000},
    {'Имя': 'Виктор', 'Отдел': 'IT', 'Зарплата': 95000}
])
print('DataFrame из списка словарей:')
df_from_records

DataFrame из списка словарей:

      Имя    Отдел  Зарплата
0    Анна       IT     75000
1   Борис  Продажи     62000
2  Виктор       IT     95000

## 2.4 С указанием индекса

**Синтаксис:** `pd.DataFrame(data, index=[...])`

Параметр `index` позволяет задать пользовательские метки строк.

In [2]:
# Создание DataFrame с пользовательским индексом
df_with_index = pd.DataFrame(
    {'Отдел': ['IT', 'Продажи', 'HR'],
     'Бюджет': [500000, 300000, 150000]},
    index=['dept_1', 'dept_2', 'dept_3']  # пользовательский индекс
)
print('DataFrame с пользовательским индексом:')
df_with_index

DataFrame с пользовательским индексом:

          Отдел  Бюджет
dept_1       IT  500000
dept_2  Продажи  300000
dept_3       HR  150000

# 3. Чтение и запись данных

pandas поддерживает чтение и запись данных в различные форматы: CSV, Excel, JSON и другие.

## 3.1 Чтение и запись CSV

**`pd.read_csv(filepath)`** — читает CSV-файл в DataFrame.
**`df.to_csv(filepath)`** — сохраняет DataFrame в CSV.

Основные параметры `read_csv`:
- `sep` — разделитель (по умолчанию `,`)
- `encoding` — кодировка файла
- `header` — номер строки с заголовками
- `index_col` — столбец для использования как индекс

Основные параметры `to_csv`:
- `index=False` — не сохранять индекс
- `sep` — разделитель
- `encoding` — кодировка

In [3]:
# Сохранение основного DataFrame в CSV
df.to_csv('employees.csv', index=False, encoding='utf-8')
print('Файл employees.csv сохранён')

# Чтение CSV обратно
df_loaded = pd.read_csv('employees.csv', encoding='utf-8')
print('\nЧтение из CSV:')
print(df_loaded.head())

# Сохранение с разделителем «точка с запятой» (формат Excel для России)
df.to_csv('employees_semicolon.csv', index=False, sep=';', encoding='utf-8-sig')
print('\nФайл employees_semicolon.csv сохранён (sep=;, utf-8-sig для Excel)')

Файл employees.csv сохранён

Чтение из CSV:
       Имя    Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
0     Анна       IT       28     75000  2021-03-15      4.5
1    Борис  Продажи       35     62000  2019-07-20      3.8
2   Виктор       IT       42     95000  2015-01-10      4.9
3   Галина       HR       31     58000  2020-11-01      4.2
4  Дмитрий  Продажи       29     64000  2022-05-18      NaN

Файл employees_semicolon.csv сохранён (sep=;, utf-8-sig для Excel)

In [8]:
df_loaded

       Имя    Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
0     Анна       IT       28     75000  2021-03-15      4.5
1    Борис  Продажи       35     62000  2019-07-20      3.8
2   Виктор       IT       42     95000  2015-01-10      4.9
3   Галина       HR       31     58000  2020-11-01      4.2
4  Дмитрий  Продажи       29     64000  2022-05-18      NaN
5    Елена       IT       38     82000  2018-09-05      4.7

## 3.2 Чтение и запись Excel

**`pd.read_excel(filepath)`** — читает Excel-файл (.xlsx, .xls).
**`df.to_excel(filepath)`** — сохраняет DataFrame в Excel.

Требуется установка: `pip install openpyxl`

In [ ]:
# Для работы с Excel необходима библиотека openpyxl
# !pip install openpyxl  # раскомментируйте при необходимости

# Сохранение в Excel
df.to_excel('employees.xlsx', index=False, sheet_name='Сотрудники')
print('Файл employees.xlsx сохранён')

# Чтение из Excel
df_excel = pd.read_excel('employees.xlsx', sheet_name='Сотрудники')
print('\nЧтение из Excel:')
print(df_excel.head())

Файл employees.xlsx сохранён

Чтение из Excel:
       Имя    Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
0     Анна       IT       28     75000  2021-03-15      4.5
1    Борис  Продажи       35     62000  2019-07-20      3.8
2   Виктор       IT       42     95000  2015-01-10      4.9
3   Галина       HR       31     58000  2020-11-01      4.2
4  Дмитрий  Продажи       29     64000  2022-05-18      NaN

## 3.3 Чтение и запись JSON

**`pd.read_json(filepath_or_string)`** — читает JSON в DataFrame.
**`df.to_json(filepath)`** — сохраняет DataFrame в JSON.

Параметр `orient` определяет формат JSON: `'records'`, `'split'`, `'index'`, `'columns'`, `'values'`.

In [ ]:
# Сохранение в JSON (формат records — массив объектов)
json_str = df[['Имя', 'Отдел', 'Зарплата']].to_json(orient='records', force_ascii=False, indent=2)
print('JSON представление:')
print(json_str[:300], '...')

# Сохранение в файл
df.to_json('employees.json', orient='records', force_ascii=False, indent=2)
print('\nФайл employees.json сохранён')

# Чтение из JSON
df_json = pd.read_json('employees.json')
print('\nЧтение из JSON:')
print(df_json[['Имя', 'Отдел', 'Зарплата']].head())

JSON представление:
[
  {
    "Имя":"Анна",
    "Отдел":"IT",
    "Зарплата":75000
  },
  {
    "Имя":"Борис",
    "Отдел":"Продажи",
    "Зарплата":62000
  },
  {
    "Имя":"Виктор",
    "Отдел":"IT",
    "Зарплата":95000
  },
  {
    "Имя":"Галина",
    "Отдел":"HR",
    "Зарплата":58000
  },
  {
    "Имя":"Дмитрий", ...

Файл employees.json сохранён

Чтение из JSON:
       Имя    Отдел  Зарплата
0     Анна       IT     75000
1    Борис  Продажи     62000
2   Виктор       IT     95000
3   Галина       HR     58000
4  Дмитрий  Продажи     64000

# 4. Просмотр и базовая информация

Методы для быстрого изучения структуры и содержимого DataFrame.

## 4.1 head() и tail()

**`df.head(n)`** — первые `n` строк (по умолчанию 5).
**`df.tail(n)`** — последние `n` строк (по умолчанию 5).

In [9]:
# Первые 3 строки
print('Первые 3 строки:')
print(df.head(3))

# Последние 2 строки
print('\nПоследние 2 строки:')
df.tail(2)

Первые 3 строки:
      Имя    Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
0    Анна       IT       28     75000  2021-03-15      4.5
1   Борис  Продажи       35     62000  2019-07-20      3.8
2  Виктор       IT       42     95000  2015-01-10      4.9

Последние 2 строки:

       Имя    Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
4  Дмитрий  Продажи       29     64000  2022-05-18      NaN
5    Елена       IT       38     82000  2018-09-05      4.7

## 4.2 shape, dtypes, columns, index, values

- **`df.shape`** — кортеж `(строк, столбцов)`
- **`df.dtypes`** — типы данных каждого столбца
- **`df.columns`** — список имён столбцов
- **`df.index`** — объект индекса
- **`df.values`** — данные в виде numpy-массива
- **`len(df)`** — количество строк

In [ ]:
print('Размер DataFrame:', df.shape)
print('Количество строк:', len(df))
print('\nСтолбцы:')
print(df.columns.tolist())
print('\nИндекс:', df.index.tolist())
print('\nТипы данных:')
print(df.dtypes)

Размер DataFrame: (6, 6)
Количество строк: 6

Столбцы:
['Имя', 'Отдел', 'Возраст', 'Зарплата', 'Дата_приёма', 'Рейтинг']

Индекс: [0, 1, 2, 3, 4, 5]

Типы данных:
Имя                    object
Отдел                  object
Возраст                 int64
Зарплата                int64
Дата_приёма    datetime64[ns]
Рейтинг               float64
dtype: object

In [ ]:
# Получение данных в виде numpy-массива
print('Значения (numpy array):')
print(df.values)

Значения (numpy array):
[['Анна' 'IT' 28 75000 Timestamp('2021-03-15 00:00:00') 4.5]
 ['Борис' 'Продажи' 35 62000 Timestamp('2019-07-20 00:00:00') 3.8]
 ['Виктор' 'IT' 42 95000 Timestamp('2015-01-10 00:00:00') 4.9]
 ['Галина' 'HR' 31 58000 Timestamp('2020-11-01 00:00:00') 4.2]
 ['Дмитрий' 'Продажи' 29 64000 Timestamp('2022-05-18 00:00:00') nan]
 ['Елена' 'IT' 38 82000 Timestamp('2018-09-05 00:00:00') 4.7]]

## 4.3 info() и describe()

**`df.info()`** — сводная информация: типы, количество непустых значений, использование памяти.


**`df.describe()`** — базовая статистика по числовым столбцам.

In [ ]:
# Сводная информация о DataFrame
print('Информация о DataFrame:')
df.info()

Информация о DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Имя          6 non-null      object
 1   Отдел        6 non-null      object
 2   Возраст      6 non-null      int64
 3   Зарплата     6 non-null      int64
 4   Дата_приёма  6 non-null      datetime64[ns]
 5   Рейтинг      5 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 420.0+ bytes

In [ ]:
# Статистика по числовым столбцам
print('Описательная статистика:')
df.describe()

Описательная статистика:

         Возраст      Зарплата          Дата_приёма   Рейтинг
count   6.000000      6.000000                    6  5.000000
mean   33.833333  72666.666667  2019-08-11 20:00:00  4.420000
min    28.000000  58000.000000  2015-01-10 00:00:00  3.800000
25%    29.500000  62500.000000  2018-11-23 12:00:00  4.200000
50%    33.000000  69500.000000  2020-03-11 00:00:00  4.500000
75%    37.250000  80250.000000  2021-02-09 12:00:00  4.700000
max    42.000000  95000.000000  2022-05-18 00:00:00  4.900000
std     5.492419  14109.098719                  NaN  0.432435

# 5. Выбор данных (индексация)

pandas предоставляет гибкие способы доступа к данным по меткам (`loc`) и позициям (`iloc`).

## 5.1 Выбор столбцов

**`df['col']`** — возвращает столбец как Series.

**`df.col`** — атрибутный доступ (работает если нет пробелов в имени).

**`df[['col1', 'col2']]`** — выбор нескольких столбцов (возвращает DataFrame).

In [ ]:
# Выбор одного столбца
print('Столбец Имя (Series):')
print(df['Имя'])

# Выбор нескольких столбцов
print('\nВыбор двух столбцов (DataFrame):')
print(df[['Имя', 'Зарплата']])

Столбец Имя (Series):
0       Анна
1      Борис
2     Виктор
3     Галина
4    Дмитрий
5      Елена
Name: Имя, dtype: object

Выбор двух столбцов (DataFrame):
       Имя  Зарплата
0     Анна     75000
1    Борис     62000
2   Виктор     95000
3   Галина     58000
4  Дмитрий     64000
5    Елена     82000

## 5.2 Выбор строк: loc и iloc

**`df.loc[label]`** — доступ по метке индекса (label-based).

**`df.iloc[pos]`** — доступ по числовой позиции (position-based).

Синтаксис срезов:
- `df.loc[start:end]` — включает обе границы
- `df.iloc[start:end]` — не включает правую границу

In [ ]:
# Доступ по метке индекса (loc)
print('Строка с индексом 0 (loc):')
print(df.loc[0])

# Срез строк по меткам
print('\nСтроки 1-3 (loc):')
print(df.loc[1:3])

Строка с индексом 0 (loc):
Имя                           Анна
Отдел                           IT
Возраст                         28
Зарплата                     75000
Дата_приёма    2021-03-15 00:00:00
Рейтинг                        4.5
Name: 0, dtype: object

Строки 1-3 (loc):
      Имя    Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
1   Борис  Продажи       35     62000  2019-07-20      3.8
2  Виктор       IT       42     95000  2015-01-10      4.9
3  Галина       HR       31     58000  2020-11-01      4.2

In [ ]:
# Доступ по числовой позиции (iloc)
print('Строка на позиции 0 (iloc):')
print(df.iloc[0])

# Срез строк по позиции
print('\nСтроки 0-2 (iloc):')
print(df.iloc[0:3])

# Последняя строка
print('\nПоследняя строка (iloc[-1]):')
print(df.iloc[-1])

Строка на позиции 0 (iloc):
Имя                           Анна
Отдел                           IT
Возраст                         28
Зарплата                     75000
Дата_приёма    2021-03-15 00:00:00
Рейтинг                        4.5
Name: 0, dtype: object

Строки 0-2 (iloc):
      Имя    Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
0    Анна       IT       28     75000  2021-03-15      4.5
1   Борис  Продажи       35     62000  2019-07-20      3.8
2  Виктор       IT       42     95000  2015-01-10      4.9

Последняя строка (iloc[-1]):
Имя                          Елена
Отдел                           IT
Возраст                         38
Зарплата                     82000
Дата_приёма    2018-09-05 00:00:00
Рейтинг                        4.7
Name: 5, dtype: object

## 5.3 Выбор ячейки: loc, iloc, at, iat

**`df.loc[row, col]`** — ячейка по метке строки и имени столбца.

**`df.iloc[row_idx, col_idx]`** — ячейка по числовым позициям.

**`df.at[row, col]`** — быстрый скалярный доступ по меткам.

**`df.iat[row_idx, col_idx]`** — быстрый скалярный доступ по позициям.

In [ ]:
# Выбор конкретной ячейки через loc
print('df.loc[0, "Имя"]:', df.loc[0, 'Имя'])

# Выбор ячейки через iloc
print('df.iloc[0, 0]:', df.iloc[0, 0])

# Быстрый доступ через at
print('df.at[2, "Зарплата"]:', df.at[2, 'Зарплата'])

# Быстрый доступ через iat
print('df.iat[2, 3]:', df.iat[2, 3])

# Выбор строк и столбцов одновременно
print('\nСтроки 0-2, столбцы Имя и Зарплата:')
print(df.loc[0:2, ['Имя', 'Зарплата']])

df.loc[0, "Имя"]: Анна
df.iloc[0, 0]: Анна
df.at[2, "Зарплата"]: 95000
df.iat[2, 3]: 95000

Строки 0-2, столбцы Имя и Зарплата:
      Имя  Зарплата
0    Анна     75000
1   Борис     62000
2  Виктор     95000

# 6. Фильтрация данных

Фильтрация позволяет выбирать строки, удовлетворяющие заданным условиям.

## 6.1 Фильтрация по условию

**Синтаксис:** `df[df['col'] > значение]`

Операторы сравнения: `>`, `<`, `>=`, `<=`, `==`, `!=`

Логические операторы:
- `&` — И (AND)
- `|` — ИЛИ (OR)
- `~` — НЕ (NOT)

> Каждое условие при использовании `&` или `|` нужно оборачивать в скобки!

In [ ]:
# Сотрудники с зарплатой выше 70 000
print('Зарплата > 70 000:')
print(df[df['Зарплата'] > 70000])

# Несколько условий (И)
print('\nОтдел IT И возраст < 40:')
print(df[(df['Отдел'] == 'IT') & (df['Возраст'] < 40)])

# Несколько условий (ИЛИ)
print('\nОтдел IT ИЛИ зарплата > 80 000:')
print(df[(df['Отдел'] == 'IT') | (df['Зарплата'] > 80000)])

Зарплата > 70 000:
      Имя Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
0    Анна    IT       28     75000  2021-03-15      4.5
2  Виктор    IT       42     95000  2015-01-10      4.9
5   Елена    IT       38     82000  2018-09-05      4.7

Отдел IT И возраст < 40:
     Имя Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
0   Анна    IT       28     75000  2021-03-15      4.5
5  Елена    IT       38     82000  2018-09-05      4.7

Отдел IT ИЛИ зарплата > 80 000:
      Имя Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
0    Анна    IT       28     75000  2021-03-15      4.5
2  Виктор    IT       42     95000  2015-01-10      4.9
5   Елена    IT       38     82000  2018-09-05      4.7

## 6.2 query(), isin(), between(), str.contains()

**`df.query('выражение')`** — фильтрация строковым запросом.

**`df['col'].isin([...])`** — проверка вхождения значения в список.

**`df['col'].between(a, b)`** — значения в диапазоне от `a` до `b` включительно.

**`df['col'].str.contains('паттерн')`** — поиск подстроки в строковом столбце.

In [ ]:
# Фильтрация через query
print('query: Зарплата > 70000 и Отдел IT:')
print(df.query('Зарплата > 70000 and Отдел == "IT"'))

# isin — проверка вхождения в список
print('\nisin: Отдел — IT или HR:')
print(df[df['Отдел'].isin(['IT', 'HR'])])

# between — диапазон значений
print('\nbetween: Возраст от 30 до 38:')
print(df[df['Возраст'].between(30, 38)])

# str.contains — поиск подстроки
print('\nstr.contains: Имя содержит букву "и":')
print(df[df['Имя'].str.contains('и', case=False, na=False)])

query: Зарплата > 70000 и Отдел IT:
      Имя Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
0    Анна    IT       28     75000  2021-03-15      4.5
2  Виктор    IT       42     95000  2015-01-10      4.9
5   Елена    IT       38     82000  2018-09-05      4.7

isin: Отдел — IT или HR:
      Имя Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
0    Анна    IT       28     75000  2021-03-15      4.5
2  Виктор    IT       42     95000  2015-01-10      4.9
3  Галина    HR       31     58000  2020-11-01      4.2
5   Елена    IT       38     82000  2018-09-05      4.7

between: Возраст от 30 до 38:
      Имя    Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
1   Борис  Продажи       35     62000  2019-07-20      3.8
3  Галина       HR       31     58000  2020-11-01      4.2
5   Елена       IT       38     82000  2018-09-05      4.7

str.contains: Имя содержит букву "и":
       Имя    Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
1    Борис  Продажи       35     62000  2019-07-20      3.8
2   Виктор       IT       42     95000  2015-01-10      4.9
3   Галина       HR       31     58000  2020-11-01      4.2
4  Дмитрий  Продажи       29     64000  2022-05-18      NaN

# 7. Изменение данных

Добавление, удаление и изменение столбцов и строк DataFrame.

## 7.1 Добавление и удаление столбцов

**`df['new_col'] = values`** — добавление нового столбца.

**`df.drop(columns=['col'])`** — удаление столбцов.

**`df.drop('col', axis=1)`** — альтернативный синтаксис.

**`df.assign(new_col=values)`** — создаёт новый DataFrame с дополнительным столбцом.

In [ ]:
# Создаём копию для изменений
df2 = df.copy()

# Добавление нового столбца
df2['Премия'] = df2['Зарплата'] * 0.1
print('После добавления столбца Премия:')
print(df2[['Имя', 'Зарплата', 'Премия']])

# Удаление столбца
df3 = df2.drop(columns=['Премия'])
print('\nПосле удаления столбца Премия:')
print(df3.columns.tolist())

# assign — создаёт новый DataFrame без изменения исходного
df_assigned = df.assign(
    Премия=df['Зарплата'] * 0.1,
    Итого=lambda x: x['Зарплата'] + x['Зарплата'] * 0.1
)
print('\nassign — добавление нескольких столбцов:')
print(df_assigned[['Имя', 'Зарплата', 'Премия', 'Итого']])

После добавления столбца Премия:
       Имя  Зарплата  Премия
0     Анна     75000  7500.0
1    Борис     62000  6200.0
2   Виктор     95000  9500.0
3   Галина     58000  5800.0
4  Дмитрий     64000  6400.0
5    Елена     82000  8200.0

После удаления столбца Премия:
['Имя', 'Отдел', 'Возраст', 'Зарплата', 'Дата_приёма', 'Рейтинг']

assign — добавление нескольких столбцов:
       Имя  Зарплата  Премия     Итого
0     Анна     75000  7500.0   82500.0
1    Борис     62000  6200.0   68200.0
2   Виктор     95000  9500.0  104500.0
3   Галина     58000  5800.0   63800.0
4  Дмитрий     64000  6400.0   70400.0
5    Елена     82000  8200.0   90200.0

## 7.2 Удаление строк и переименование столбцов

**`df.drop(index=[0, 1])`** — удаление строк по метке индекса.

**`df.rename(columns={'old': 'new'})`** — переименование столбцов.

In [ ]:
# Удаление строк по индексу
df_no_rows = df.drop(index=[0, 1])
print('После удаления строк 0 и 1:')
print(df_no_rows[['Имя', 'Отдел']])

# Переименование столбцов
df_renamed = df.rename(columns={
    'Имя': 'Сотрудник',
    'Зарплата': 'Оклад',
    'Дата_приёма': 'ДатаПриёма'
})
print('\nПосле переименования столбцов:')
print(df_renamed.columns.tolist())

После удаления строк 0 и 1:
       Имя    Отдел
2   Виктор       IT
3   Галина       HR
4  Дмитрий  Продажи
5    Елена       IT

После переименования столбцов:
['Сотрудник', 'Отдел', 'Возраст', 'Оклад', 'ДатаПриёма', 'Рейтинг']

## 7.3 Изменение типов и замена значений

**`df['col'].astype(type)`** — преобразование типа данных столбца.

**`df['col'].replace(old, new)`** — замена значений.

In [ ]:
# Изменение типа столбца
df_typed = df.copy()
df_typed['Возраст'] = df_typed['Возраст'].astype(float)
print('Тип Возраст после astype(float):', df_typed['Возраст'].dtype)

# Замена значений
df_replaced = df.copy()
df_replaced['Отдел'] = df_replaced['Отдел'].replace({'IT': 'Информационные технологии', 'HR': 'Кадры'})
print('\nПосле замены значений в столбце Отдел:')
print(df_replaced['Отдел'])

Тип Возраст после astype(float): float64

После замены значений в столбце Отдел:
0    Информационные технологии
1                      Продажи
2    Информационные технологии
3                        Кадры
4                      Продажи
5    Информационные технологии
Name: Отдел, dtype: object

# 8. Работа с пропущенными значениями (NaN)

Пропущенные значения (`NaN`, `None`) — распространённая проблема реальных данных.
pandas предоставляет удобные инструменты для их поиска, удаления и заполнения.

## 8.1 Обнаружение пропусков

**`df.isna()`** / **`df.isnull()`** — маска True/False для пропущенных значений.

**`df.notna()`** — обратная маска.

**`df.isna().sum()`** — количество пропусков по каждому столбцу.

In [ ]:
print('Маска пропущенных значений:')
print(df.isna())

print('\nКоличество пропусков по столбцам:')
print(df.isna().sum())

print('\nОбщее количество пропусков:', df.isna().sum().sum())

Маска пропущенных значений:
     Имя  Отдел  Возраст  Зарплата  Дата_приёма  Рейтинг
0  False  False    False     False        False    False
1  False  False    False     False        False    False
2  False  False    False     False        False    False
3  False  False    False     False        False    False
4  False  False    False     False        False     True
5  False  False    False     False        False    False

Количество пропусков по столбцам:
Имя            0
Отдел          0
Возраст        0
Зарплата       0
Дата_приёма    0
Рейтинг        1
dtype: int64

Общее количество пропусков: 1

## 8.2 Удаление строк с пропусками

**`df.dropna()`** — удаляет строки, содержащие хотя бы один NaN.

**`df.dropna(subset=['col'])`** — удаляет строки с NaN только в указанных столбцах.

**`df.dropna(thresh=n)`** — оставляет строки с минимум `n` непустыми значениями.

In [ ]:
# Удаление строк с любым NaN
df_no_nan = df.dropna()
print('После dropna() — строк осталось:', len(df_no_nan))
print(df_no_nan[['Имя', 'Рейтинг']])

# Удаление строк с NaN только в столбце Рейтинг
df_no_rating_nan = df.dropna(subset=['Рейтинг'])
print('\nПосле dropna(subset=["Рейтинг"]) — строк осталось:', len(df_no_rating_nan))
print(df_no_rating_nan[['Имя', 'Рейтинг']])

После dropna() — строк осталось: 5
      Имя  Рейтинг
0    Анна      4.5
1   Борис      3.8
2  Виктор      4.9
3  Галина      4.2
5   Елена      4.7

После dropna(subset=["Рейтинг"]) — строк осталось: 5
      Имя  Рейтинг
0    Анна      4.5
1   Борис      3.8
2  Виктор      4.9
3  Галина      4.2
5   Елена      4.7

## 8.3 Заполнение пропусков

**`df.fillna(value)`** — заполнение константой.

**`df.fillna(method='ffill')`** — заполнение предыдущим значением (forward fill).

**`df.fillna(method='bfill')`** — заполнение следующим значением (backward fill).

**`df.interpolate()`** — интерполяция числовых значений.

In [ ]:
# Заполнение NaN средним значением
mean_rating = df['Рейтинг'].mean()
df_filled = df.copy()
df_filled['Рейтинг'] = df_filled['Рейтинг'].fillna(mean_rating)
print('После fillna(mean):')
print(df_filled[['Имя', 'Рейтинг']])

# Forward fill (заполнение предыдущим значением)
df_ffill = df.copy()
df_ffill['Рейтинг'] = df_ffill['Рейтинг'].ffill()
print('\nПосле ffill:')
print(df_ffill[['Имя', 'Рейтинг']])

# Интерполяция
df_interp = df.copy()
df_interp['Рейтинг'] = df_interp['Рейтинг'].interpolate()
print('\nПосле interpolate:')
print(df_interp[['Имя', 'Рейтинг']])

После fillna(mean):
       Имя  Рейтинг
0     Анна     4.50
1    Борис     3.80
2   Виктор     4.90
3   Галина     4.20
4  Дмитрий     4.42
5    Елена     4.70

После ffill:
       Имя  Рейтинг
0     Анна      4.5
1    Борис      3.8
2   Виктор      4.9
3   Галина      4.2
4  Дмитрий      4.2
5    Елена      4.7

После interpolate:
       Имя  Рейтинг
0     Анна     4.50
1    Борис     3.80
2   Виктор     4.90
3   Галина     4.20
4  Дмитрий     4.45
5    Елена     4.70

# 9. Сортировка

pandas позволяет сортировать DataFrame по значениям столбцов или по индексу.

## 9.1 sort_values()

**`df.sort_values('col')`** — сортировка по возрастанию.

**`df.sort_values('col', ascending=False)`** — по убыванию.

**`df.sort_values(['col1', 'col2'])`** — по нескольким столбцам.


Параметр `na_position`: `'last'` (NaN в конец) или `'first'` (NaN в начало).

In [ ]:
# Сортировка по зарплате (по возрастанию)
print('Сортировка по зарплате (↑):')
print(df.sort_values('Зарплата')[['Имя', 'Зарплата']])

# Сортировка по убыванию
print('\nСортировка по зарплате (↓):')
print(df.sort_values('Зарплата', ascending=False)[['Имя', 'Зарплата']])

# Сортировка по нескольким столбцам
print('\nСортировка по отделу и зарплате:')
print(df.sort_values(['Отдел', 'Зарплата'], ascending=[True, False])[['Имя', 'Отдел', 'Зарплата']])

Сортировка по зарплате (↑):
       Имя  Зарплата
3   Галина     58000
1    Борис     62000
4  Дмитрий     64000
0     Анна     75000
5    Елена     82000
2   Виктор     95000

Сортировка по зарплате (↓):
       Имя  Зарплата
2   Виктор     95000
5    Елена     82000
0     Анна     75000
4  Дмитрий     64000
1    Борис     62000
3   Галина     58000

Сортировка по отделу и зарплате:
       Имя    Отдел  Зарплата
3   Галина       HR     58000
2   Виктор       IT     95000
5    Елена       IT     82000
0     Анна       IT     75000
4  Дмитрий  Продажи     64000
1    Борис  Продажи     62000

## 9.2 sort_index(), nlargest(), nsmallest()

**`df.sort_index()`** — сортировка по индексу.

**`df.nlargest(n, 'col')`** — `n` строк с наибольшими значениями.

**`df.nsmallest(n, 'col')`** — `n` строк с наименьшими значениями.

In [ ]:
# Сортировка по индексу (в обратном порядке)
print('Сортировка по индексу (↓):')
print(df.sort_index(ascending=False)[['Имя', 'Зарплата']])

# Топ-3 по зарплате
print('\n3 самых высокооплачиваемых сотрудника (nlargest):')
print(df.nlargest(3, 'Зарплата')[['Имя', 'Зарплата']])

# Топ-3 по минимальной зарплате
print('\n3 сотрудника с наименьшей зарплатой (nsmallest):')
print(df.nsmallest(3, 'Зарплата')[['Имя', 'Зарплата']])

Сортировка по индексу (↓):
       Имя  Зарплата
5    Елена     82000
4  Дмитрий     64000
3   Галина     58000
2   Виктор     95000
1    Борис     62000
0     Анна     75000

3 самых высокооплачиваемых сотрудника (nlargest):
      Имя  Зарплата
2  Виктор     95000
5   Елена     82000
0    Анна     75000

3 сотрудника с наименьшей зарплатой (nsmallest):
       Имя  Зарплата
3   Галина     58000
1    Борис     62000
4  Дмитрий     64000

# 10. Группировка и агрегация

Группировка позволяет вычислять агрегатные показатели по подгруппам данных.

## 10.1 groupby() с агрегатными функциями

**Синтаксис:** `df.groupby('col').агрегат()`

Основные агрегатные функции: `.mean()`, `.sum()`, `.count()`, `.min()`, `.max()`, `.std()`

In [ ]:
# Средняя зарплата по отделам
print('Средняя зарплата по отделам:')
print(df.groupby('Отдел')['Зарплата'].mean())

# Несколько агрегатов сразу
print('\nСтатистика по отделам:')
print(df.groupby('Отдел')[['Зарплата', 'Возраст']].agg(['mean', 'min', 'max']))

# Разные функции для разных столбцов
print('\nРазные агрегаты для разных столбцов:')
print(df.groupby('Отдел').agg({
    'Зарплата': 'mean',
    'Возраст': 'max',
    'Имя': 'count'
}))

Средняя зарплата по отделам:
Отдел
HR         58000.0
IT         84000.0
Продажи    63000.0
Name: Зарплата, dtype: float64

Статистика по отделам:
        Зарплата               Возраст
            mean    min    max    mean min max
Отдел
HR       58000.0  58000  58000    31.0  31  31
IT       84000.0  75000  95000    36.0  28  42
Продажи  63000.0  62000  64000    32.0  29  35

Разные агрегаты для разных столбцов:
         Зарплата  Возраст  Имя
Отдел
HR        58000.0       31    1
IT        84000.0       42    3
Продажи   63000.0       35    2

## 10.2 Множественная группировка и сводные таблицы

**`df.groupby(['col1', 'col2']).size()`** — группировка по нескольким столбцам.

**`df.pivot_table(values, index, columns, aggfunc)`** — сводная таблица.

In [ ]:
# Добавим столбец для примера
df_ext = df.copy()
df_ext['Уровень'] = ['Средний', 'Старший', 'Старший', 'Средний', 'Средний', 'Старший']

# Группировка по двум столбцам
print('Количество сотрудников по Отделу и Уровню:')
print(df_ext.groupby(['Отдел', 'Уровень']).size())

# Сводная таблица
print('\nСводная таблица — средняя зарплата:')
pivot = df_ext.pivot_table(
    values='Зарплата',
    index='Отдел',
    columns='Уровень',
    aggfunc='mean',
    fill_value=0
)
print(pivot)

Количество сотрудников по Отделу и Уровню:
Отдел    Уровень
HR       Средний    1
IT       Средний    1
         Старший    2
Продажи  Средний    1
         Старший    1
dtype: int64

Сводная таблица — средняя зарплата:
Уровень  Средний  Старший
Отдел
HR       58000.0      0.0
IT       75000.0  88500.0
Продажи  64000.0  62000.0

# 11. Объединение DataFrame

pandas предоставляет несколько способов объединения данных: конкатенацию и слияние (аналог SQL JOIN).

## 11.1 concat() — вертикальное и горизонтальное объединение

**`pd.concat([df1, df2])`** — вертикальное объединение (добавление строк).

**`pd.concat([df1, df2], axis=1)`** — горизонтальное объединение (добавление столбцов).

Параметр `ignore_index=True` сбрасывает индекс в результирующем DataFrame.

In [ ]:
# Создаём дополнительный DataFrame новых сотрудников
new_employees = pd.DataFrame({
    'Имя': ['Игорь', 'Карина'],
    'Отдел': ['Маркетинг', 'HR'],
    'Возраст': [27, 33],
    'Зарплата': [55000, 61000],
    'Дата_приёма': pd.to_datetime(['2023-01-10', '2023-03-01']),
    'Рейтинг': [4.0, 3.9]
})

# Вертикальное объединение
df_concat = pd.concat([df, new_employees], ignore_index=True)
print('После вертикального объединения (concat):')
print(df_concat[['Имя', 'Отдел', 'Зарплата']])

После вертикального объединения (concat):
       Имя      Отдел  Зарплата
0     Анна         IT     75000
1    Борис    Продажи     62000
2   Виктор         IT     95000
3   Галина         HR     58000
4  Дмитрий    Продажи     64000
5    Елена         IT     82000
6    Игорь  Маркетинг     55000
7   Карина         HR     61000

## 11.2 merge() — слияние по ключу

**Синтаксис:** `pd.merge(df1, df2, on='key', how='inner')`

Типы слияния (`how`):
- `'inner'` — только совпадающие строки (по умолчанию)
- `'left'` — все строки из левого + совпадения из правого
- `'right'` — все строки из правого + совпадения из левого
- `'outer'` — все строки из обоих DataFrame

In [ ]:
# Слияние сотрудников с информацией об отделах
print('departments:')
print(departments)

print('\nСотрудники:')
print(df)

# Inner join (только совпадающие отделы)
df_inner = pd.merge(df, departments, on='Отдел', how='inner')
print('\n\nInner merge (сотрудники + отделы):')
print(df_inner[['Имя', 'Отдел', 'Зарплата', 'Бюджет', 'Руководитель']])

# Left join (все отделы, NaN если сотрудник не найден)
df_right = pd.merge(df, departments, on='Отдел', how='right')
print('\nRight merge:')
print(df_left[['Имя', 'Отдел', 'Зарплата', 'Бюджет', 'Руководитель']])

departments:
       Отдел  Бюджет Руководитель
0         IT  500000       Иванов
1    Продажи  300000       Петров
2         HR  150000     Сидорова
3  Маркетинг  200000       Козлов

Сотрудники:
       Имя    Отдел  Возраст  Зарплата Дата_приёма  Рейтинг
0     Анна       IT       28     75000  2021-03-15      4.5
1    Борис  Продажи       35     62000  2019-07-20      3.8
2   Виктор       IT       42     95000  2015-01-10      4.9
3   Галина       HR       31     58000  2020-11-01      4.2
4  Дмитрий  Продажи       29     64000  2022-05-18      NaN
5    Елена       IT       38     82000  2018-09-05      4.7


Inner merge (сотрудники + отделы):
       Имя    Отдел  Зарплата  Бюджет Руководитель
0     Анна       IT     75000  500000       Иванов
1    Борис  Продажи     62000  300000       Петров
2   Виктор       IT     95000  500000       Иванов
3   Галина       HR     58000  150000     Сидорова
4  Дмитрий  Продажи     64000  300000       Петров
5    Елена       IT     82000  500000       Иванов

Right merge:
       Имя      Отдел  Зарплата  Бюджет Руководитель
0     Анна         IT   75000.0  500000       Иванов
1   Виктор         IT   95000.0  500000       Иванов
2    Елена         IT   82000.0  500000       Иванов
3    Борис    Продажи   62000.0  300000       Петров
4  Дмитрий    Продажи   64000.0  300000       Петров
5   Галина         HR   58000.0  150000     Сидорова
6      NaN  Маркетинг       NaN  200000       Козлов

## 11.3 join() — объединение по индексу

**`df1.join(df2)`** — объединяет DataFrame по индексу.

Удобен когда ключ совпадения — это индекс одного из DataFrame.

In [ ]:
# Пример join по индексу
df_a = df[['Имя', 'Зарплата']].copy()
df_b = pd.DataFrame(
    {'Бонус': [5000, 3000, 8000, 2000, 4000, 6000]},
    index=df.index
)

df_joined = df_a.join(df_b)
print('После join по индексу:')
print(df_joined)

После join по индексу:
       Имя  Зарплата  Бонус
0     Анна     75000   5000
1    Борис     62000   3000
2   Виктор     95000   8000
3   Галина     58000   2000
4  Дмитрий     64000   4000
5    Елена     82000   6000

# 12. Применение функций

pandas позволяет применять функции к столбцам, строкам и отдельным элементам.

## 12.1 apply() для столбцов и строк

**`df['col'].apply(func)`** — применяет функцию к каждому элементу столбца.

**`df.apply(func, axis=0)`** — применяет функцию к каждому столбцу.

**`df.apply(func, axis=1)`** — применяет функцию к каждой строке.

In [ ]:
# apply к столбцу
def classify_salary(salary):
    if salary >= 80000:
        return 'Высокая'
    elif salary >= 65000:
        return 'Средняя'
    else:
        return 'Низкая'

df_apply = df.copy()
df_apply['Категория_зп'] = df_apply['Зарплата'].apply(classify_salary)
print('Классификация зарплаты через apply:')
print(df_apply[['Имя', 'Зарплата', 'Категория_зп']])

# apply к строке (axis=1)
df_apply['Сводка'] = df_apply.apply(
    lambda row: f"{row['Имя']} ({row['Отдел']}, {row['Зарплата']} руб.)",
    axis=1
)
print('\nСводка по строкам (axis=1):')
print(df_apply['Сводка'])

Классификация зарплаты через apply:
       Имя  Зарплата Категория_зп
0     Анна     75000      Средняя
1    Борис     62000       Низкая
2   Виктор     95000      Высокая
3   Галина     58000       Низкая
4  Дмитрий     64000       Низкая
5    Елена     82000      Высокая

Сводка по строкам (axis=1):
0            Анна (IT, 75000 руб.)
1      Борис (Продажи, 62000 руб.)
2          Виктор (IT, 95000 руб.)
3          Галина (HR, 58000 руб.)
4    Дмитрий (Продажи, 64000 руб.)
5           Елена (IT, 82000 руб.)
Name: Сводка, dtype: object

## 12.2 apply() к столбцам (axis=0) и лямбда-функции

**`df.apply(func, axis=0)`** — применяет функцию к каждому столбцу целиком (получает Series).

**Лямбда-функции** — краткий синтаксис для простых преобразований: `lambda x: выражение`

In [ ]:
# apply к каждому столбцу (axis=0)
numeric_cols = df[['Возраст', 'Зарплата', 'Рейтинг']].copy()
print('Минимум и максимум по каждому столбцу:')
print(numeric_cols.apply(lambda col: col.max() - col.min(), axis=0))

# Лямбда-функции
df_lambda = df.copy()
df_lambda['Зарплата_тыс'] = df_lambda['Зарплата'].apply(lambda x: round(x / 1000, 1))
print('\nЗарплата в тысячах рублей:')
print(df_lambda[['Имя', 'Зарплата', 'Зарплата_тыс']])

Минимум и максимум по каждому столбцу:
Возраст        14.0
Зарплата    37000.0
Рейтинг         1.1
dtype: float64

Зарплата в тысячах рублей:
       Имя  Зарплата  Зарплата_тыс
0     Анна     75000          75.0
1    Борис     62000          62.0
2   Виктор     95000          95.0
3   Галина     58000          58.0
4  Дмитрий     64000          64.0
5    Елена     82000          82.0

## 12.3 map() — поэлементное применение

**`df['col'].map(dict_or_func)`** — заменяет значения столбца, используя словарь или функцию.

**`df.map(func)`** (или `df.applymap(func)` в старых версиях) — применяет функцию к каждой ячейке.

In [ ]:
# map со словарём — замена значений
dept_map = {'IT': 'Технологии', 'Продажи': 'Sales', 'HR': 'Кадры'}
df_mapped = df.copy()
df_mapped['Отдел_EN'] = df_mapped['Отдел'].map(dept_map)
print('map со словарём:')
print(df_mapped[['Имя', 'Отдел', 'Отдел_EN']])

# DataFrame.map — к каждой ячейке
numeric_df = df[['Возраст', 'Зарплата']].copy()
result = numeric_df.map(lambda x: x * 1.1 if pd.notna(x) else x)
print('\nДанные увеличены на 10% (df.map):')
print(result)

map со словарём:
       Имя    Отдел    Отдел_EN
0     Анна       IT  Технологии
1    Борис  Продажи       Sales
2   Виктор       IT  Технологии
3   Галина       HR       Кадры
4  Дмитрий  Продажи       Sales
5    Елена       IT  Технологии

Данные увеличены на 10% (df.map):
   Возраст  Зарплата
0     30.8   82500.0
1     38.5   68200.0
2     46.2  104500.0
3     34.1   63800.0
4     31.9   70400.0
5     41.8   90200.0

# 13. Работа со строками

pandas предоставляет акцессор `.str` для векторизованных строковых операций.
Все методы работают поэлементно, без необходимости явного цикла.

In [ ]:
# Создаём DataFrame для демонстрации строковых операций
df_str = pd.DataFrame({
    'ФИО': ['  Анна Иванова  ', 'Борис  Петров', 'Виктор СИДОРОВ', 'галина козлова'],
    'Email': ['anna@company.ru', 'boris@company.ru', 'viktor@firm.com', 'galina@company.ru'],
    'Телефон': ['+7(495)123-45-67', '+7(812)987-65-43', '+7(495)111-22-33', '+7(812)444-55-66']
})
print('Исходные данные:')
print(df_str)

Исходные данные:
                ФИО              Email           Телефон
0    Анна Иванова      anna@company.ru  +7(495)123-45-67
1     Борис  Петров   boris@company.ru  +7(812)987-65-43
2    Виктор СИДОРОВ    viktor@firm.com  +7(495)111-22-33
3    галина козлова  galina@company.ru  +7(812)444-55-66

## 13.1 Регистр, пробелы, замена

- **`.str.lower()`** / **`.str.upper()`** / **`.str.title()`** — изменение регистра
- **`.str.strip()`** / **`.str.lstrip()`** / **`.str.rstrip()`** — удаление пробелов
- **`.str.replace('old', 'new')`** — замена подстроки

In [ ]:
# Нормализация регистра и пробелов
df_clean = df_str.copy()
df_clean['ФИО'] = df_clean['ФИО'].str.strip().str.title()
print('После strip() и title():')
print(df_clean['ФИО'])

После strip() и title():
0      Анна Иванова
1     Борис  Петров
2    Виктор Сидоров
3    Галина Козлова
Name: ФИО, dtype: object

In [ ]:
# Замена подстроки
df_clean['Email'] = df_clean['Email'].str.replace('@company.ru', '@corp.ru', regex=False)
print('\nПосле замены домена:')
print(df_clean['Email'])

После замены домена:
0       anna@corp.ru
1      boris@corp.ru
2    viktor@firm.com
3     galina@corp.ru
Name: Email, dtype: object

In [ ]:
# Верхний регистр
print('\nВсе имена заглавными буквами:')
print(df['Имя'].str.upper())

Все имена заглавными буквами:
0       АННА
1      БОРИС
2     ВИКТОР
3     ГАЛИНА
4    ДМИТРИЙ
5      ЕЛЕНА
Name: Имя, dtype: object

## 13.2 split(), contains(), len(), startswith(), endswith(), extract()

- **`.str.split('delim')`** — разбиение по разделителю
- **`.str.contains('pattern')`** — проверка наличия подстроки
- **`.str.len()`** — длина строки
- **`.str.startswith('prefix')`** / **`.str.endswith('suffix')`** — проверка начала/конца
- **`.str.extract(r'(\d+)')`** — извлечение по регулярному выражению

In [ ]:
# Разбиение строки
print('Разбиение ФИО на части:')
print(df_str['ФИО'].str.strip().str.split(' ', expand=True))

Разбиение ФИО на части:
        0        1       2
0    Анна  Иванова    None
1   Борис           Петров
2  Виктор  СИДОРОВ    None
3  галина  козлова    None

In [ ]:
# Проверка вхождения подстроки
print('\nEmail с доменом company.ru:')
print(df_str[df_str['Email'].str.contains('company.ru')])

Email с доменом company.ru:
                ФИО              Email           Телефон
0    Анна Иванова      anna@company.ru  +7(495)123-45-67
1     Борис  Петров   boris@company.ru  +7(812)987-65-43
3    галина козлова  galina@company.ru  +7(812)444-55-66

In [ ]:
# Длина строки
print('\nДлина email-адресов:')
print(df_str['Email'].str.len())

Длина email-адресов:
0    15
1    16
2    15
3    17
Name: Email, dtype: int64

In [ ]:
# startswith и endswith
print('\nEmail оканчивается на .com:')
print(df_str['Email'].str.endswith('.com'))

Email оканчивается на .com:
0    False
1    False
2     True
3    False
Name: Email, dtype: bool

In [ ]:
# Извлечение кода города через regex
print('\nКод города из номера телефона (extract):')
print(df_str['Телефон'].str.extract(r'\((\d{3})\)'))

Код города из номера телефона (extract):
     0
0  495
1  812
2  495
3  812

# 14. Работа с датами

pandas предоставляет акцессор `.dt` для работы с датами и временем.
Даты должны быть конвертированы в тип `datetime64` с помощью `pd.to_datetime()`.

## 14.1 Преобразование в datetime и извлечение компонентов

**`pd.to_datetime(col)`** — конвертация в datetime.

Компоненты даты через `.dt`:
- `.dt.year`, `.dt.month`, `.dt.day`
- `.dt.hour`, `.dt.minute`, `.dt.second`
- `.dt.dayofweek` — день недели (0=понедельник)
- `.dt.day_name()` — название дня недели
- `.dt.date`, `.dt.time`

In [ ]:
# Убедимся, что столбец Дата_приёма имеет тип datetime
print('Тип Дата_приёма:', df['Дата_приёма'].dtype)

# Извлечение компонентов
df_dates = df.copy()
df_dates['Год'] = df_dates['Дата_приёма'].dt.year
df_dates['Месяц'] = df_dates['Дата_приёма'].dt.month
df_dates['День'] = df_dates['Дата_приёма'].dt.day
df_dates['День_недели'] = df_dates['Дата_приёма'].dt.day_name()

print('\nКомпоненты даты приёма:')
print(df_dates[['Имя', 'Дата_приёма', 'Год', 'Месяц', 'День', 'День_недели']])

Тип Дата_приёма: datetime64[ns]

Компоненты даты приёма:
       Имя Дата_приёма   Год  Месяц  День День_недели
0     Анна  2021-03-15  2021      3    15      Monday
1    Борис  2019-07-20  2019      7    20    Saturday
2   Виктор  2015-01-10  2015      1    10    Saturday
3   Галина  2020-11-01  2020     11     1      Sunday
4  Дмитрий  2022-05-18  2022      5    18   Wednesday
5    Елена  2018-09-05  2018      9     5   Wednesday

## 14.2 Временные интервалы и вычисления с датами

**`pd.Timedelta()`** — создание временного интервала.

Арифметика с датами: вычитание дат даёт `Timedelta`, добавление `Timedelta` к дате — новую дату.

In [ ]:
# Текущая дата
today = pd.Timestamp('2026-01-01')  # фиксированная дата для воспроизводимости

# Вычисление стажа
df_dates['Стаж_дней'] = (today - df_dates['Дата_приёма']).dt.days
df_dates['Стаж_лет'] = (df_dates['Стаж_дней'] / 365.25).round(1)

print('Стаж сотрудников:')
print(df_dates[['Имя', 'Дата_приёма', 'Стаж_дней', 'Стаж_лет']])

Стаж сотрудников:
       Имя Дата_приёма  Стаж_дней  Стаж_лет
0     Анна  2021-03-15       1753       4.8
1    Борис  2019-07-20       2357       6.5
2   Виктор  2015-01-10       4009      11.0
3   Галина  2020-11-01       1887       5.2
4  Дмитрий  2022-05-18       1324       3.6
5    Елена  2018-09-05       2675       7.3

In [ ]:
# Добавление временного интервала
df_dates['Дата_пробации'] = df_dates['Дата_приёма'] + pd.Timedelta(days=90)
print('\nДата окончания испытательного срока:')
print(df_dates[['Имя', 'Дата_приёма', 'Дата_пробации']])

Дата окончания испытательного срока:
       Имя Дата_приёма Дата_пробации
0     Анна  2021-03-15    2021-06-13
1    Борис  2019-07-20    2019-10-18
2   Виктор  2015-01-10    2015-04-10
3   Галина  2020-11-01    2021-01-30
4  Дмитрий  2022-05-18    2022-08-16
5    Елена  2018-09-05    2018-12-04

## 14.3 Ресемплинг временных рядов

**`df.resample('период')`** — агрегация данных по временным периодам.

Часто используемые периоды: `'D'` — день, `'W'` — неделя, `'ME'` — конец месяца, `'YE'` — конец года.

In [ ]:
# Создаём временной ряд для демонстрации resample
dates = pd.date_range(start='2025-01-01', end='2025-12-31', freq='D')
ts_df = pd.DataFrame({
    'Дата': dates,
    'Продажи': np.random.randint(100, 1000, size=len(dates))
}).set_index('Дата')
ts_df.head(5)

            Продажи
Дата
2025-01-01      843
2025-01-02      571
2025-01-03      467
2025-01-04      298
2025-01-05      388

In [ ]:
# Ресемплинг по месяцам
monthly = ts_df.resample('ME').sum()
print('Продажи по месяцам (ресемплинг):')
print(monthly)

Продажи по месяцам (ресемплинг):
            Продажи
Дата
2025-01-31    15850
2025-02-28    15648
2025-03-31    19306
2025-04-30    18198
2025-05-31    17159
2025-06-30    15757
2025-07-31    18171
2025-08-31    17033
2025-09-30    17222
2025-10-31    17080
2025-11-30    16995
2025-12-31    17266

# 15. Статистические методы

pandas содержит богатый набор методов для вычисления статистических показателей.

## 15.1 Основные статистики

- **`.mean()`** — среднее арифметическое
- **`.median()`** — медиана
- **`.mode()`** — мода (наиболее частое значение)
- **`.std()`** — стандартное отклонение
- **`.var()`** — дисперсия
- **`.min()`** / **`.max()`** — минимум/максимум
- **`.sum()`** — сумма
- **`.quantile(q)`** — квантиль

In [ ]:
# Основные статистики по зарплате
salary = df['Зарплата']

print(f'Средняя зарплата:    {salary.mean():.0f} руб.')
print(f'Медианная зарплата:  {salary.median():.0f} руб.')
print(f'Мода зарплаты:       {salary.mode()[0]:.0f} руб.')
print(f'Стандартное откл.:   {salary.std():.0f} руб.')
print(f'Дисперсия:           {salary.var():.0f}')
print(f'Минимум:             {salary.min():.0f} руб.')
print(f'Максимум:            {salary.max():.0f} руб.')
print(f'Сумма:               {salary.sum():.0f} руб.')
print(f'25-й квантиль:       {salary.quantile(0.25):.0f} руб.')
print(f'75-й квантиль:       {salary.quantile(0.75):.0f} руб.')

Средняя зарплата:    72667 руб.
Медианная зарплата:  69500 руб.
Мода зарплаты:       58000 руб.
Стандартное откл.:   14109 руб.
Дисперсия:           199066667
Минимум:             58000 руб.
Максимум:            95000 руб.
Сумма:               436000 руб.
25-й квантиль:       62500 руб.
75-й квантиль:       80250 руб.

## 15.2 value_counts(), nunique(), unique(), corr(), cov()

- **`.value_counts()`** — частоты уникальных значений
- **`.nunique()`** — количество уникальных значений
- **`.unique()`** — массив уникальных значений
- **`df.corr()`** — матрица корреляции (Пирсон по умолчанию)
- **`df.cov()`** — ковариационная матрица

In [ ]:
# Частоты значений по отделам
print('Распределение по отделам (value_counts):')
print(df['Отдел'].value_counts())

Распределение по отделам (value_counts):
Отдел
IT         3
Продажи    2
HR         1
Name: count, dtype: int64

In [ ]:
print('\nКоличество уникальных отделов (nunique):', df['Отдел'].nunique())
print('Уникальные отделы (unique):', df['Отдел'].unique())

Количество уникальных отделов (nunique): 3
Уникальные отделы (unique): ['IT' 'Продажи' 'HR']

In [ ]:
# Корреляционная матрица
print('\nМатрица корреляции:')
print(df[['Возраст', 'Зарплата', 'Рейтинг']].corr())

Матрица корреляции:
           Возраст  Зарплата   Рейтинг
Возраст   1.000000  0.719204  0.471616
Зарплата  0.719204  1.000000  0.897738
Рейтинг   0.471616  0.897738  1.000000

In [ ]:
# Ковариационная матрица
print('\nКовариационная матрица:')
print(df[['Возраст', 'Зарплата']].cov())

Ковариационная матрица:
               Возраст      Зарплата
Возраст      30.166667  5.573333e+04
Зарплата  55733.333333  1.990667e+08

# 16. Преобразования и реструктуризация

Инструменты для изменения формы и структуры DataFrame.

## 16.1 Транспонирование и melt()

**`df.T`** — транспонирование (строки ↔ столбцы).

In [ ]:
# Транспонирование
df_numeric = df[['Имя', 'Возраст', 'Зарплата', 'Рейтинг']].set_index('Имя')
print('Транспонированный DataFrame:')
print(df_numeric.T)

Транспонированный DataFrame:
Имя          Анна    Борис   Виктор   Галина  Дмитрий    Елена
Возраст      28.0     35.0     42.0     31.0     29.0     38.0
Зарплата  75000.0  62000.0  95000.0  58000.0  64000.0  82000.0
Рейтинг       4.5      3.8      4.9      4.2      NaN      4.7

## 16.2 pivot(), stack(), unstack()

**`df.pivot_table(index, columns, values)`** — сводная талбица.

**`df.stack()`** — перенос столбцов в индекс (добавляет уровень в индекс).

**`df.unstack()`** — обратная операция.

In [ ]:
df_right

,Имя,Отдел,Возраст,Зарплата,Дата_приёма,Рейтинг,Бюджет,Руководитель
0,Анна,IT,28.0,75000.0,2021-03-15,4.5,500000,Иванов
1,Виктор,IT,42.0,95000.0,2015-01-10,4.9,500000,Иванов
2,Елена,IT,38.0,82000.0,2018-09-05,4.7,500000,Иванов
3,Борис,Продажи,35.0,62000.0,2019-07-20,3.8,300000,Петров
4,Дмитрий,Продажи,29.0,64000.0,2022-05-18,NaN,300000,Петров
5,Галина,HR,31.0,58000.0,2020-11-01,4.2,150000,Сидорова
6,NaN,Маркетинг,NaN,NaN,NaT,NaN,200000,Козлов

In [ ]:
# pivot — длинный формат → широкий (обратно к melt)
df_pivot = df_right.pivot_table(
    index='Руководитель',
    columns='Отдел',
    values='Зарплата',
    aggfunc='mean',
    fill_value=0)


print('После pivot (широкий формат):')
print(df_pivot)

После pivot (широкий формат):
Отдел              HR       IT  Продажи
Руководитель
Иванов            0.0  84000.0      0.0
Петров            0.0      0.0  63000.0
Сидорова      58000.0      0.0      0.0

## 16.3 explode(), get_dummies(), cut(), qcut()

**`df.explode('col')`** — разворачивание списков в отдельные строки.

**`pd.get_dummies(df['col'])`** — one-hot кодирование категориальных переменных.

**`pd.cut(series, bins)`** — разбивка на интервалы по заданным границам.

**`pd.qcut(series, q)`** — разбивка на квантильные интервалы.

In [ ]:
# explode — разворачивание списков
df_skills = pd.DataFrame({
    'Имя': ['Анна', 'Борис', 'Виктор'],
    'Навыки': [['Python', 'SQL'], ['Excel', 'PowerBI'], ['Python', 'R', 'SQL']]
})
df_skills

      Имя            Навыки
0    Анна     [Python, SQL]
1   Борис  [Excel, PowerBI]
2  Виктор  [Python, R, SQL]

In [ ]:
print('После explode:')
df_skills.explode('Навыки')

После explode:

      Имя   Навыки
0    Анна   Python
0    Анна      SQL
1   Борис    Excel
1   Борис  PowerBI
2  Виктор   Python
2  Виктор        R
2  Виктор      SQL

In [ ]:
# get_dummies — one-hot кодирование
dummies = pd.get_dummies(df['Отдел'], prefix='Отдел')
print('One-hot кодирование отделов:')
print(dummies)

One-hot кодирование отделов:
   Отдел_HR  Отдел_IT  Отдел_Продажи
0     False      True          False
1     False     False           True
2     False      True          False
3      True     False          False
4     False     False           True
5     False      True          False

In [ ]:
# pd.cut — биннинг по заданным границам
df_binned = df.copy()
df_binned['Возр_группа'] = pd.cut(
    df['Возраст'],
    bins=[20, 30, 40, 50],
    labels=['20-30', '30-40', '40-50']
)
print('\nВозрастные группы (pd.cut):')
print(df_binned[['Имя', 'Возраст', 'Возр_группа']])

Возрастные группы (pd.cut):
       Имя  Возраст Возр_группа
0     Анна       28       20-30
1    Борис       35       30-40
2   Виктор       42       40-50
3   Галина       31       30-40
4  Дмитрий       29       20-30
5    Елена       38       30-40

In [ ]:
# pd.qcut — биннинг по квантилям
df_binned['Зп_квантиль'] = pd.qcut(
    df['Зарплата'],
    q=3,
    labels=['Низкая', 'Средняя', 'Высокая']
)
print('\nКвартили зарплаты (pd.qcut):')
print(df_binned[['Имя', 'Зарплата', 'Зп_квантиль']])

Квартили зарплаты (pd.qcut):
       Имя  Зарплата Зп_квантиль
0     Анна     75000     Средняя
1    Борис     62000      Низкая
2   Виктор     95000     Высокая
3   Галина     58000      Низкая
4  Дмитрий     64000     Средняя
5    Елена     82000     Высокая

# 17. Дубликаты

Поиск и удаление повторяющихся строк.

## 17.1 Обнаружение и удаление дубликатов

**`df.duplicated()`** — возвращает маску True для дублирующихся строк.

**`df.drop_duplicates()`** — удаляет дублирующиеся строки, оставляя первое вхождение.

**`df.drop_duplicates(subset=['col'])`** — проверяет дубли только по указанным столбцам.


Параметр `keep`: `'first'` (оставить первое), `'last'` (оставить последнее), `False` (удалить все).

In [ ]:
# Создаём DataFrame с дубликатами
df_with_dupes = pd.concat([df, df.iloc[[0, 2]]], ignore_index=True)
print('DataFrame с дубликатами:')
print(df_with_dupes[['Имя', 'Отдел', 'Зарплата']])

DataFrame с дубликатами:
       Имя    Отдел  Зарплата
0     Анна       IT     75000
1    Борис  Продажи     62000
2   Виктор       IT     95000
3   Галина       HR     58000
4  Дмитрий  Продажи     64000
5    Елена       IT     82000
6     Анна       IT     75000
7   Виктор       IT     95000

In [ ]:
# Маска дубликатов
print('\nМаска дубликатов (duplicated):')
print(df_with_dupes.duplicated())

Маска дубликатов (duplicated):
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
dtype: bool

In [ ]:
# Количество дубликатов
print('\nКоличество дубликатов:', df_with_dupes.duplicated().sum())

Количество дубликатов: 2

In [ ]:
# Удаление всех дубликатов
df_no_dupes = df_with_dupes.drop_duplicates()
print('После drop_duplicates():')
print(df_no_dupes[['Имя', 'Отдел', 'Зарплата']])
print('Строк после удаления дубликатов:', len(df_no_dupes))

После drop_duplicates():
       Имя    Отдел  Зарплата
0     Анна       IT     75000
1    Борис  Продажи     62000
2   Виктор       IT     95000
3   Галина       HR     58000
4  Дмитрий  Продажи     64000
5    Елена       IT     82000
Строк после удаления дубликатов: 6

In [ ]:
# Удаление дубликатов по конкретному столбцу
df_unique_dept = df_with_dupes.drop_duplicates(subset=['Отдел'])
print('\nУдаление по столбцу Отдел (первый сотрудник из каждого отдела):')
print(df_unique_dept[['Имя', 'Отдел']])

Удаление по столбцу Отдел (первый сотрудник из каждого отдела):
      Имя    Отдел
0    Анна       IT
1   Борис  Продажи
3  Галина       HR

# 18. Настройки отображения

pandas позволяет настраивать формат вывода DataFrame в Jupyter/Colab.

## 18.1 pd.set_option() и pd.reset_option()

Основные опции:
- **`display.max_rows`** — максимальное количество отображаемых строк
- **`display.max_columns`** — максимальное количество отображаемых столбцов
- **`display.max_colwidth`** — максимальная ширина столбца (символов)
- **`display.float_format`** — формат отображения чисел с плавающей точкой
- **`display.precision`** — число знаков после запятой

**`pd.reset_option('all')`** — сброс всех настроек к значениям по умолчанию.

In [ ]:
# Текущие настройки
print('Текущие значения:')
print('max_rows:', pd.get_option('display.max_rows'))
print('max_columns:', pd.get_option('display.max_columns'))
print('max_colwidth:', pd.get_option('display.max_colwidth'))

Текущие значения:
max_rows: 60
max_columns: 20
max_colwidth: 50

In [ ]:
# Установка новых настроек
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_colwidth', 200)
pd.set_option('display.float_format', '{:.2f}'.format)

print('\nПосле настройки float_format — числа с 2 знаками после запятой:')
print(df[['Имя', 'Зарплата', 'Рейтинг']])

После настройки float_format — числа с 2 знаками после запятой:
       Имя  Зарплата  Рейтинг
0     Анна     75000     4.50
1    Борис     62000     3.80
2   Виктор     95000     4.90
3   Галина     58000     4.20
4  Дмитрий     64000      NaN
5    Елена     82000     4.70

In [ ]:
# Установка числа знаков после запятой
pd.set_option('display.precision', 3)
print('Точность 3 знака:')
print(df[['Имя', 'Рейтинг']])

Точность 3 знака:
       Имя  Рейтинг
0     Анна     4.50
1    Борис     3.80
2   Виктор     4.90
3   Галина     4.20
4  Дмитрий      NaN
5    Елена     4.70

In [ ]:
# Сброс всех настроек
pd.reset_option('all')
print('\nНастройки сброшены до значений по умолчанию')
print('max_rows после сброса:', pd.get_option('display.max_rows'))

Настройки сброшены до значений по умолчанию
max_rows после сброса: 60

/tmp/ipykernel_4435/424199633.py:2: FutureWarning: data_manager option is deprecated and will be removed in a future version. Only the BlockManager will be available.
  pd.reset_option('all')
/tmp/ipykernel_4435/424199633.py:2: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  pd.reset_option('all')

# Итоги

Данное руководство охватывает все основные возможности pandas DataFrame:

| Раздел | Ключевые методы |
|--------|-----------------|
| Создание | `pd.DataFrame()` |
| Чтение/запись | `read_csv`, `to_csv`, `read_excel`, `to_json` |
| Просмотр | `head`, `tail`, `info`, `describe`, `shape` |
| Индексация | `loc`, `iloc`, `at`, `iat` |
| Фильтрация | булевы маски, `query`, `isin`, `between` |
| Изменение | `assign`, `drop`, `rename`, `replace`, `astype` |
| NaN | `isna`, `dropna`, `fillna`, `interpolate` |
| Сортировка | `sort_values`, `sort_index`, `nlargest` |
| Группировка | `groupby`, `agg`, `pivot_table` |
| Объединение | `concat`, `merge`, `join` |
| Функции | `apply`, `map`, `lambda` |
| Строки | `.str.*` методы |
| Даты | `pd.to_datetime`, `.dt.*`, `Timedelta`, `resample` |
| Статистика | `mean`, `median`, `std`, `corr`, `value_counts` |
| Реструктуризация | `melt`, `pivot`, `stack`, `explode`, `get_dummies` |
| Дубликаты | `duplicated`, `drop_duplicates` |
| Настройки | `pd.set_option`, `pd.reset_option` |

---
**Полезные ресурсы:**
- [Официальная документация pandas](https://pandas.pydata.org/docs/)
- [pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)
- [10 Minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html)